name: create_snow_change
description: Create ServiceNow CHG ticket
author: bwhitehead0
inputs:
  snow_url:
    description: ServiceNow URL (e.g., https://my-company.service-now.com)
    required: true
  snow_user:
    description: ServiceNow username (Username + password or token are required)
    required: true
  snow_password:
    description: ServiceNow password (Username + password or token are required)
    required: true
  snow_client_id:
    description: "ServiceNow Client ID for oAuth Token auth (Required: User + pass + client ID + client secret)"
    required: false
  snow_client_secret:
    description: "ServiceNow Client Secret for oAuth Token auth (Required: User + pass + client ID + client secret)"
    required: false
  debug:
    description: Enable debug output
    required: false
    default: "false"
  snow_timeout:
    description: "Timeout for ServiceNow API call (default: 60)"
    required: false
    default: "60"
  change_ticket_number:
    description: ServiceNow change ticket number
    required: false
outputs:
  change_detail:
    description: The full JSON response from the ServiceNow API
    value: ${{ steps.get_change_detail.outputs.change_detail }}
  change_sys_id:
    description: The sys_id of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_sys_id }}
  change_type:
    description: The type of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_type }}
  change_requested_by:
    description: The user who requested the change ticket
    value: ${{ steps.get_change_detail.outputs.change_requested_by }}
  change_cab_reviewed:
    description: The CAB review status of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_cab_reviewed }}
  change_state:
    description: The state of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_state }}
  change_state_code:
    description: The state code of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_state_code }}
  change_start_date:
    description: The start date of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_start_date }}
  change_end_date:
    description: The end date of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_end_date }}
  change_cmdb_ci:
    description: The CMDB CI of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_cmdb_ci }}
  change_cmdb_ci_sys_id:
    description: The CMDB CI sys_id of the change ticket
    value: ${{ steps.get_change_detail.outputs.change_cmdb_ci_sys_id }}

runs:
  using: composite
  steps:
    - name: Get ServiceNow Change Ticket Detail
      id: get_change_detail
      run: |
        response=$(${{ github.action_path }}/assets/get_snow_change.sh \
        -c "${{ inputs.change_ticket_number }}" \
        -l "${{ inputs.snow_url }}" \
        -u "${{ inputs.snow_user }}" \
        -p "${{ inputs.snow_password }}" \
        -o "${{ inputs.snow_timeout }}" \
        -C "${{ inputs.snow_client_id }}" \
        -S "${{ inputs.snow_client_secret }}" \
        -D "${{ inputs.debug }}")

        status=$?

        if [ "${{ inputs.debug }}" = "true" ]; then
          printf '%s' "Change Ticket Detail:\n$response"
        fi

        if [[ $status -eq 0 ]]; then
          chg_sys_id=$(printf '%s' $response | jq -r '.sys_id.value')
          chg_type=$(printf '%s' $response | jq -r '.type.value')
          chg_requested_by=$(printf '%s' $response | jq -r '.requested_by.display_value')
          chg_cab_reviewed=$(printf '%s' $response | jq -r '.u_cab_reviewed.display_value')
          chg_state=$(printf '%s' $response | jq -r '.state.display_value')
          chg_state_code=$(printf '%s' $response | jq -r '.state.value')
          chg_start_date=$(printf '%s' $response | jq -r '.start_date.value')
          chg_end_date=$(printf '%s' $response | jq -r '.end_date.value')
          cmdb_ci=$(printf '%s' $response | jq -r '.cmdb_ci.display_value')
          cmdb_ci_sys_id=$(printf '%s' $response | jq -r '.cmdb_ci.value')

          printf '%s' "change_sys_id=$chg_sys_id" >> $GITHUB_OUTPUT
          printf '%s' "change_type=$chg_type" >> $GITHUB_OUTPUT
          printf '%s' "change_requested_by=$chg_requested_by" >> $GITHUB_OUTPUT
          printf '%s' "change_cab_reviewed=$chg_cab_reviewed" >> $GITHUB_OUTPUT
          printf '%s' "change_state=$chg_state" >> $GITHUB_OUTPUT
          printf '%s' "change_state_code=$chg_state_code" >> $GITHUB_OUTPUT
          printf '%s' "change_start_date=$chg_start_date" >> $GITHUB_OUTPUT
          printf '%s' "change_end_date=$chg_end_date" >> $GITHUB_OUTPUT
          printf '%s' "change_cmdb_ci=$cmdb_ci" >> $GITHUB_OUTPUT
          printf '%s' "change_cmdb_ci_sys_id=$cmdb_ci_sys_id" >> $GITHUB_OUTPUT
        fi

        printf '%s' "change_detail=$response" >> $GITHUB_OUTPUT

      shell: bash

branding:
  icon: "cloud-snow"
  color: "orange"